# Development Dockerfile
FROM node:18-alpine

# ตั้งค่า working directory
WORKDIR /app

# คัดลอก package.json และ package-lock.json
COPY package*.json ./

# ติดตั้ง dependencies
RUN npm install

# คัดลอกโค้ดทั้งหมด
COPY . .

ENV PORT=3002 \
	HOST=0.0.0.0 \
	BROWSER=none \
	CHOKIDAR_USEPOLLING=true \
	WATCHPACK_POLLING=true

# เปิด port 3002
EXPOSE 3002

# รันคำสั่งเริ่มต้น development server
CMD ["npm", "start"]